#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("EightBot.MonoDroid.CheatCode.Resource", IsApplication=true)]

namespace EightBot.MonoDroid.CheatCode
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int toasty_popout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int toasty_popup = 2130968577;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int contra = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int toasty = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int ivMain_contra = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int ivMain_toasty = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int rlMain_ImageContainer = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int tvMain_CommandHeader = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int tvMain_CommandList = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int tvMain_CommandListHeader = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int tvMain_LastCommand = 2131165185;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int contra = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int toasty = 2131034113;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
